# Repaso de cositas de python

In [122]:
from funciones import *
# def matrizAntisimetrica(v):
#     print(v)
#     # S = 
a = matrizAntisimetrica(2)

2


In [123]:
import numpy as np
from funciones import *
a = np.array(1)
print(a)
b = np.array([[1,2,3]])
a = matrizAntisimetrica(b)

1
[[1 2 3]]


In [124]:
# x = input("Ingrese un valor")
# print("usted ingreso", x)
for i in range(1,11):
    pass
    # print(i)

## Listas, tuplas y diccionarios

In [125]:
marca_de_sensores = ['SIAP', 'VAISALA', 'CAMPBELL']
q = marca_de_sensores[2]
print('Esta {} en la lista? Rta = {}'.format(q, q in marca_de_sensores))
q = 'Coastal'
print('Esta {} en la lista? Rta = {}'.format(q, q in marca_de_sensores))

Esta CAMPBELL en la lista? Rta = True
Esta Coastal en la lista? Rta = False


In [126]:
telefonos = {'Pedro':2652, 'Juan':4545, 'Marcos':4889}
print(telefonos)

# insertamos
telefonos['Cristian'] = 4568
print(telefonos)

# borramos
del telefonos['Juan']
print(telefonos)

# Armamos una lista del diccionario
print(list(telefonos))

# me pregunto si andres esta en la lista

print('Andres' in telefonos)


{'Pedro': 2652, 'Juan': 4545, 'Marcos': 4889}
{'Pedro': 2652, 'Juan': 4545, 'Marcos': 4889, 'Cristian': 4568}
{'Pedro': 2652, 'Marcos': 4889, 'Cristian': 4568}
['Pedro', 'Marcos', 'Cristian']
False


Ecuaciones en linea de $H(s)$ 

Ecuaciones en bloque
$$ H(s) = \begin{bmatrix} h_{11}(s) & h_{12}(s) \\
h_{21}(s) & h_{22}(s)\end{bmatrix}$$

In [127]:
print(dir(np.linalg))


['LinAlgError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'cholesky', 'cond', 'det', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


In [128]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)
print(np.linalg.det(A))
A = np.array([[10,2,3], [4,5,6], [7,8,9]])
print(np.linalg.det(A))
B = np.linalg.inv(A)
print(np.dot(A,B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0
-27.0
[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [-2.77555756e-17  1.00000000e+00  1.33226763e-15]
 [ 6.93889390e-17 -2.66453526e-15  1.00000000e+00]]
