# Matriz de Rotacion

In [1]:
import numpy as np
from funciones import *
v = np.array([1,0,0])
v_antisimertrica = matrizAntisimetrica3x3(v)
print(v_antisimertrica)
resultWithMatriz = np.dot( v_antisimertrica,np.array([0,1,0]))
print(resultWithMatriz)
# print(result = np.dot(v,v.T))

[[ 0  0  0]
 [ 0  0 -1]
 [ 0  1  0]]
[0 0 1]


## Figura off line con plotly

In [2]:
from plotly.offline import init_notebook_mode, iplot
# from plotly.graph_objs import *
import plotly.graph_objs as px
print(dir(px))
init_notebook_mode(connected=True)         # initiate notebook for offline plot

trace0 = px.Scatter(
  x=[1, 2, 3, 4],
  y=[10, 15, 13, 17]
)
trace1 = px.Scatter(
  x=[1, 2, 3, 4],
  y=[16, 5, 11, 9]
)

iplot([trace0, trace1])               # use plotly.offline.iplot for offline plot

['AngularAxis', 'Annotation', 'Annotations', 'Bar', 'Barpolar', 'Box', 'Candlestick', 'Carpet', 'Choropleth', 'Choroplethmapbox', 'ColorBar', 'Cone', 'Contour', 'Contourcarpet', 'Contours', 'Data', 'Densitymapbox', 'ErrorX', 'ErrorY', 'ErrorZ', 'Figure', 'FigureWidget', 'Font', 'Frame', 'Frames', 'Funnel', 'Funnelarea', 'Heatmap', 'Heatmapgl', 'Histogram', 'Histogram2d', 'Histogram2dContour', 'Histogram2dcontour', 'Icicle', 'Image', 'Indicator', 'Isosurface', 'Layout', 'Legend', 'Line', 'Margin', 'Marker', 'Mesh3d', 'Ohlc', 'Parcats', 'Parcoords', 'Pie', 'Pointcloud', 'RadialAxis', 'Sankey', 'Scatter', 'Scatter3d', 'Scattercarpet', 'Scattergeo', 'Scattergl', 'Scattermapbox', 'Scatterpolar', 'Scatterpolargl', 'Scattersmith', 'Scatterternary', 'Scene', 'Splom', 'Stream', 'Streamtube', 'Sunburst', 'Surface', 'Table', 'Trace', 'Treemap', 'Violin', 'Volume', 'Waterfall', 'XAxis', 'XBins', 'YAxis', 'YBins', 'ZAxis', 'bar', 'barpolar', 'box', 'candlestick', 'carpet', 'choropleth', 'choropleth

## Figura on line con plotly

In [3]:
import plotly.express as px

# Crear datos de ejemplo
data = {
    'x': [1, 2, 3, 4],
    'y': [10, 15, 13, 17],
    'category': ['A', 'B', 'A', 'B']
}

# Crear un DataFrame de Pandas (o usar los datos directamente)
df = pd.DataFrame(data)

# Definir un diccionario de etiquetas personalizadas
labels_dict = {
    'x': 'Eje X Personalizado',
    'y': 'Eje Y Personalizado',
    'category': 'Categoría Personalizada'
}

# Crear el gráfico de líneas con etiquetas personalizadas
fig = px.line(
    df,
    x='x',
    y='y',
    color='category',
    labels=labels_dict,  # Aplicar las etiquetas personalizadas
    title='Gráfico de Líneas con Etiquetas Personalizadas'
)

# Mostrar el gráfico
fig.show()

NameError: name 'pd' is not defined

In [ ]:
import plotly.express as px
print(dir(px.line))
# trace0 = px.line(
#   x=[1, 2, 3, 4],
#   y=[10, 15, 13, 17],
#   title='Gráfico de Dispersión Interactivo',
  
  
# )
fig = px.line(
  x=[1, 2, 3, 4],
  y=[16, 5, 11, 9],
  title='Gráfico de Dispersión Interactivo',
  labels={'x': 'Eje X', 'y': 'Eje Y'},
  line_shape='linear',  # Forma de las líneas
  render_mode='auto' ,
  width = 1000,
  height = 500
)
# # Personalizar el eje x
# fig.update_xaxes(
#     title_text="Eje X Personalizado",
#     range=[0, 6],  # Rango personalizado para el eje y
#     # tickvals=[1, 2, 3, 4],  # Valores en los ticks del eje x
#     # ticktext=["A", "B", "C", "D"],  # Etiquetas personalizadas para los ticks
# )

# # Personalizar el eje y
# fig.update_yaxes(
#     title_text="Eje Y Personalizado",
#     range=[0, 20],  # Rango personalizado para el eje y
# )

# Configurar la leyenda
fig.update_layout(
    legend=dict(
        title="Leyenda Personalizada",  # Título de la leyenda
        orientation="h",  # Orientación horizontal
        x=0.5,  # Posición en el eje X (0-1)
        y=1.05,  # Posición en el eje Y (ajustar según necesidad)
    )
)

# Mostrar el gráfico
fig.show()

['__annotations__', '__builtins__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']


In [21]:
import plotly.graph_objects as go


fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[1, 2, 3, 4, 5],
    y=[1, 2, 3, 4, 5],
    mode='lines', 
    name="WMOS",
    line=dict(color="Green",width = 10),
))

fig.add_trace(go.Scatter(
    x=[1, 2, 3, 4, 5],
    y=[5, 4, 3, 2, 1],
    name="ASDA54"
))

fig.update_layout(legend_title_text='Termómetro',
                title = r'$\text{como andas }\beta_{x}$',
                title_x=0.5,
                width=800,  # Ancho en píxeles
                height=400, # Alto en píxeles
                
                xaxis=dict(
                title=r'Tiempo $\beta$',
                    # range=[0, 10]
                ),
                
                yaxis=dict(
                    title="Eje Y",
                    # position=0.5,
                    # tickvals=[0, 5, 10],
                    # ticktext=["Inicio", "Mitad", "Fin"]
                ),           
                plot_bgcolor='lightgray', # Color de fondo del área del gráfico
                paper_bgcolor='white',  # Color de fondo del papel (fondo del gráfico)
                
                title_font=dict(
                    color='blue'),  # Color del título
                
                legend_font=dict(
                    color='gray'),  # Color de la leyenda
                
                xaxis_title_font=dict(
                    color='red'),  # Color del título del eje X
                        
                legend=dict(
                    title="Termometro",
                    x=1,
                    y=1,
                    orientation="v"),   
                margin=dict(
                    l=50,  # Márgen izquierdo
                    r=20,  # Márgen derecho
                    t=40,  # Márgen superior
                    b=40   # Márgen inferior
    )
                
                
                
                )  
fig.show()


